/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ap.coolshop.form;

import com.ap.coolshop.dal.IDal;
import com.ap.coolshop.dal.Uow;
import com.ap.coolshop.factories.Factory;
import com.ap.coolshop.middlelayer.Customer;
import com.ap.coolshop.middlelayer.ICostumer;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author ananda
 */
public class CustomerForm extends javax.swing.JFrame {

    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    ICostumer cust = null;
    IDal<ICostumer> dal;
    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() throws Exception {
        initComponents();
        setDefaultData();
    }

    private void setDefaultData() throws Exception{
        String cus = combo_customerType.getSelectedItem().toString();
        edit_billDate.setText(formatter.format(new Date()));
        String dalstr = combo_DALSelector.getSelectedItem().toString();
        dal = Factory.getObject(dalstr);
        Iterable<ICostumer> records = dal.search();
        setTableData(records);
    }    
    private void setTableData(Iterable<ICostumer> records){
        String[] columns = new String [] {"Id","Customer Name", "Phone number", "Bill Amount", "Bill date", "Address","Customer Type"};
        
        try {
            //System.out.println(records);
            Iterator<ICostumer> it = records.iterator();
            Iterator<ICostumer> it1 = records.iterator();
            
            int size = 0;
            while(it.hasNext()){
                it.next();
                size++;
            }
            
            
            Object[][] data = new Object[size][7];
            
            int i=0;
            
            while(it1.hasNext()){
                ICostumer cust = it1.next();
                data[i][0] = cust.getId();
                data[i][1] = cust.getCustomerName();
                data[i][2] = cust.getPhoneNumber();
                data[i][3] = cust.getBillAmount();
                data[i][4] = cust.getBillDate();
                data[i][5] = cust.getAddress();
                data[i][6] = cust.getCustomerType();
                i++;
            }
            TableModel tm =  new javax.swing.table.DefaultTableModel(data,columns);
            table_data.setModel(tm);
            
            table_data.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int row = table_data.rowAtPoint(evt.getPoint());
                    int col = table_data.columnAtPoint(evt.getPoint());
                    if (row >= 0 && col >= 0) {
                        
                        String custType = data[row][6].toString();
                        try {
                            cust = dal.getData(row);
                            setFormData();
                        } catch (Exception ex) {
                            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            });

            
        } catch (Exception ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combo_customerType = new javax.swing.JComboBox<>();
        edit_customerName = new javax.swing.JTextField();
        edit_phoneNumber = new javax.swing.JTextField();
        edit_billAmount = new javax.swing.JTextField();
        edit_billDate = new javax.swing.JTextField();
        edit_address = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        combo_DALSelector = new javax.swing.JComboBox<>();
        btn_uow = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_data = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Customer Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Customer type");

        jLabel3.setText("Customer name");

        jLabel4.setText("Phone number");

        jLabel5.setText("Bill Amount");

        jLabel6.setText("Bill Date");

        jLabel7.setText("Address");

        combo_customerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Lead", "Self Service", "Home Delivery" }));
        combo_customerType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_customerTypeActionPerformed(evt);
            }
        });

        edit_customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_customerNameActionPerformed(evt);
            }
        });

        edit_phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_phoneNumberActionPerformed(evt);
            }
        });

        edit_billAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_billAmountActionPerformed(evt);
            }
        });

        edit_billDate.setToolTipText("");
        edit_billDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_billDateActionPerformed(evt);
            }
        });

        edit_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_addressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_phoneNumber)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(edit_customerName)
                        .addComponent(combo_customerType, 0, 176, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_billAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(edit_billDate)
                    .addComponent(edit_address))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edit_billAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(edit_billDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(edit_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(combo_customerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(edit_customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(edit_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_add.setText("Add/Edit");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        combo_DALSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JDBC", "Hibernate" }));
        combo_DALSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_DALSelectorActionPerformed(evt);
            }
        });

        btn_uow.setText("UOW");
        btn_uow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uowActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btn_uow, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combo_DALSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(combo_DALSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_uow)
                    .addComponent(btn_refresh)
                    .addComponent(btn_save))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Customer Name", "Phone number", "Bill Amount", "Bill date", "Address", "Customer Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_data);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setCustomer() throws Exception{
        String cus = combo_customerType.getSelectedItem().toString();
        if(cust==null){
            cust = Factory.getObject(cus);
        }
        cust.setCustomerType(cus);
        cust.setCustomerName(edit_customerName.getText());
        cust.setAddress(edit_address.getText());
        if(!edit_billAmount.getText().trim().isEmpty()){
            cust.setBillAmount(Double.parseDouble(edit_billAmount.getText()));
        }
        cust.setPhoneNumber(edit_phoneNumber.getText());
        cust.setBillDate(edit_billDate.getText());
    }
    
    private void clearForm(){
        edit_customerName.setText("");
        edit_address.setText("");
        edit_billAmount.setText("");
        edit_billDate.setText(formatter.format(new Date()));
        edit_phoneNumber.setText("");
    }
    
    private void setFormData(){
        //System.out.println(cust.getCustomerName());
        
        edit_customerName.setText(cust.getCustomerName());
        edit_address.setText(cust.getAddress());
        if(cust.getBillAmount()!=null){
            edit_billAmount.setText(cust.getBillAmount().toString());
        }
        edit_billDate.setText(cust.getBillDate());
        edit_phoneNumber.setText(cust.getPhoneNumber());
        combo_customerType.setSelectedItem(cust.getCustomerType());
    }
    
    private void combo_customerTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_customerTypeActionPerformed
        String cus = combo_customerType.getSelectedItem().toString();
        try {
            cust = Factory.getObject(cus);
        } catch (Exception ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combo_customerTypeActionPerformed

    
    private void edit_customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_customerNameActionPerformed

    private void edit_phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_phoneNumberActionPerformed

    private void edit_billAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_billAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_billAmountActionPerformed

    private void edit_billDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_billDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_billDateActionPerformed

    private void edit_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_addressActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            setCustomer();
            dal.add(cust);
            Iterable<ICostumer> records = dal.getData();
            setTableData(records);
            JOptionPane.showMessageDialog(this,"Data has been successfully added!","Added!",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void combo_DALSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_DALSelectorActionPerformed
        try {
            setDefaultData();
        } catch (Exception ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combo_DALSelectorActionPerformed

    private void btn_uowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uowActionPerformed
        String dalstr = combo_DALSelector.getSelectedItem().toString();
        Uow uow = null;
        try {
            String uowString = dalstr+"Uow";
            uow = Factory.getObject(uowString);
            dal = Factory.getObject(dalstr);
            dal.setUnitOfWork(uow);
            
            ICostumer cust1 = new Customer();
            cust1.setCustomerType("Lead");
            cust1.setCustomerName("Name11 ");
            cust1.setPhoneNumber("917-8323967");

            dal.add(cust1);
            //dal.save();
            
            
            ICostumer cust2 = new Customer();
            cust2.setCustomerType("Lead");
            cust2.setCustomerName("Name12 ahs asdfasdf adlkfl");
            cust2.setPhoneNumber("917-8323967");
            dal.add(cust2);
            dal.save();
            uow.commit();

        } catch (Exception ex) {
            try {
                uow.rollback();
            } catch (Exception ex1) {
                Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex1);
            }
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_uowActionPerformed

    private void refreshData() throws Exception{
        Iterable<ICostumer> records;
        records = dal.search();
        setTableData(records);
    }
    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        try {
            refreshData();
            JOptionPane.showMessageDialog(this,"Data has been successfully loaded","Loaded!",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            dal.save();
            refreshData();
            JOptionPane.showMessageDialog(this,"Data has been successfully saved","Successfull!",JOptionPane.INFORMATION_MESSAGE);
            clearForm();
        } catch (Exception ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CustomerForm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_uow;
    private javax.swing.JComboBox<String> combo_DALSelector;
    private javax.swing.JComboBox<String> combo_customerType;
    private javax.swing.JTextField edit_address;
    private javax.swing.JTextField edit_billAmount;
    private javax.swing.JTextField edit_billDate;
    private javax.swing.JTextField edit_customerName;
    private javax.swing.JTextField edit_phoneNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_data;
    // End of variables declaration//GEN-END:variables
}
